---
kind: Namespace
apiVersion: v1
metadata:
  name: ssh

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ssh-web-console
  namespace: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-web-console
  template:
    metadata:
      labels:
        app: ssh-web-console
    spec:
      containers:
        - name: ssh-web-console
          image: 'genshen/ssh-web-console:latest'
          ports:
            - containerPort: 2222
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /home/web/conf/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
        - name: config
          configMap:
            name: ssh-web-console
            defaultMode: 420
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ssh-web-console
  namespace: ssh
data:
  config.yaml: |
    site:
      appname: ssh-web-console
      listen_addr: :2222
      runmode: prod
    prod:
      # http path of static files and views
      static_prefix: /
    ssh:
      #  io_mode: 1  # the mode reading data from ssh server: channel mode (0) OR session mode (1)
      buffer_checker_cycle_time: 60 # check buffer every { buffer_checker_cycle_time } ms. if buffer is not empty , then send buffered data back to client(browser/webSocket)

---
kind: Service
apiVersion: v1
metadata:
  name: ssh-web-console
  namespace: ssh
spec:
  selector:
    app: ssh-web-console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2222
  type: ClusterIP
