#!/usr/bin/env python3

import urllib3
import yaml

http = urllib3.PoolManager()
r = http.request('GET', 'https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml')

out = r.data.decode('unicode_escape').split('---')
out = list(map(lambda x: yaml.dump(yaml.safe_load(x)), out))

print("\n---\n".join(out))
