---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello
spec:
  rules:
    - host: hello.10.0.0.21.nip.io 
      http:
        paths:
        - path: /
          backend:
            serviceName: hello-service
            servicePort: 80
          
  rules:
    - host: hello.kube.buc.local
      http:
        paths:
        - path: /
          backend:
            serviceName: hello-service
            servicePort: 80
          

