---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello
    version: v1
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

