---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  installation_tag: My Kiali
  istio_namespace: istio-system
  deployment:
    namespace: monitor
    verbose_mode: '4'
    view_only_mode: false
    inrgess_enabled: false
  external_services:
    grafana:
      enabled: false
    prometheus:
      enabled: false
    tracing:
      enabled: true
      in_cluster_url: "http://jaeger-query.monitor:3000"
  server:
    web_root: /
  auth:
    strategy: anonymous
