---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  installation_tag: My Kiali
  istio_namespace: istio-system
  deployment:
    namespace: monitor
    verbose_mode: '4'
    view_only_mode: false
  external_services:
    grafana:
      url: 'loki-stack-grafana:80'
    prometheus:
      url: 'loki-stack-prometheus-server:80'
    tracing:
      url: 'jaeger-query:16686'
  server:
    web_root: /mykiali
