{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "loki_ingester_chunk_entries_count\n"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "\\{\\{instance\\}\\}" }
   ]
  },
  {
   "title": "Errors only",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "{stream=\"stderr\"}"
    }
   ]
  },
  {
   "title": "Output",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{stream=\"stderr\"}"
    },
    {
     "expr": "{stream=\"stdout\"}"
    }
   ]
  }
 ]
}