---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-access
  namespace: my-argocd-operator
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  orphanedResources:
    warn: false

