
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://localhost:4181
    authResponseHeaders:
      - X-Forwarded-User

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: traefik
spec:
  type: ExternalName
  externalName: localhost


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: external
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`auth.public.buc.ddns.info`)
    services:
    - name: traefik-forward-auth
      passHostHeader: false
      port: 4181
    middlewares:
      - name: traefik-forward-auth
  tls:
    certResolver: letsencrypt

