---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: external-access-helper
  labels:
    k8s-app: external-access
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: external-access
  template:
    metadata:
      labels:
        k8s-app: external-access
    spec:
      containers:
        - name: nginx
          image: 'nginx:alpine'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: httproot
              mountPath: /usr/share/nginx/html/static
            - name: service-account
              mountPath: /usr/share/nginx/html/cred
      volumes:
        - name: httproot
          configMap:
            name: static-files
            defaultMode: 0644
        - name: service-account
          secret:
              secretName: traefik-external-token
              defaultMode: 0644
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-files
  labels:
    k8s-app: external-access
data: 
  404.html: |
    <h1> 404 - Not Found </h1>
  401.html: |
    <h1> 401 - Unauthorized </h1>
  403.html: |
    <h1> 403 - Forbidden </h1>
  error.html: |
    <h1> General Error </h1>
  traefik.yaml: |
    ---
    global:
      checkNewVersion: true
      sendAnonymousUsage: false
    entryPoints:
      acme:
        address: :8000
      traefik:
        address: :8080
        http:
          middlewares: ["auth-users"]
      websecure:
        address: :8443
    providers:
      kubernetesCRD:
        endpoint: URL
        certAuthFilePath: ca.crt
        token: TOKEN
        disablePassHostHeaders: false
        namespaces: ["traefik"]
        ingressClass: external
    api:
      dashboard: true
    metrics:
      prometheus: {}
    log: {}
    accessLog:
      filePath: /var/log/traefik_access.log
    certificatesResolvers:
      letsencrypt:
        acme:
          email: foo@bar.baz
          storage: acme.json
          httpChallenge:
            entryPoint: acme


---
apiVersion: v1
kind: Service
metadata:
  name: static
  labels:
    k8s-app: external-access
spec:
  selector:
    k8s-app: external-access
  ports:
    - name: http
      port: 80
      targetPort: 80
